# Projekt: proj3
# Autor:   Vojtìch Jurka
# 
#
proj3: proj3.tex
	latex proj3.tex
	latex proj3.tex
	dvips proj3.dvi
	ps2pdf proj3.ps

clean: 
	rm proj3.ps proj3.pdf proj3.out proj3.log proj3.dvi proj3.aux
