# Projekt: Hello world!
# Autor:   Vojtìch Jurka
# 
#
proj1: proj1.tex
	latex proj1.tex
	dvips proj1.dvi -t a4
	ps2pdf proj1.ps

clean: 
	rm proj1.aux proj1.dvi proj1.log proj1.out proj1.pdf proj1.ps
